# Generated by Django 3.2 on 2021-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('starting_bid', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
