# Generated by Django 3.2.2 on 2021-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='curr_highest_bidder',
            field=models.CharField(default='No current highest bidder!', max_length=50),
        ),
    ]
